#!/bin/bash
# This is the cloud-init script used to install the build machine rpm
#
# Use this path as your user-data in the EC2 instance create:
# https://raw.githubusercontent.com/karlredgate/build-server/master/cloud-init
#

BUILDREPO=http://github.com/karlredgate/lookout-backend/releases/download

yum --enablerepo=epel --enablerepo=epel-testing \
    install --quiet -y $BUILDREPO//v1.0/lookout-backend-1.0-33.7709ec8.x86_64.rpm

# vim:autoindent expandtab sw=4
